NOTIFY_SUCCESS_EMOJI = '<tg-emoji emoji-id="5118392447394644756">✅</tg-emoji>'
NOTIFY_WALLET_EMOJI = "💰"
TELEGRAM_API_BASE = "https://api.telegram.org"
TELEGRAM_HTTP_TIMEOUT_SEC = 5
TELEGRAM_PARSE_MODE_HTML = "HTML"
