AUTO_DRAIN_IDLE_WHEN_DISABLED_SEC = 60
CLEANUP_IDLE_WHEN_DISABLED_SEC = 300
SYNTHETIC_IDLE_WHEN_DISABLED_SEC = 300

SYNTHETIC_REPAIR_REASON = "probe_synthetic_self_heal"
SYNTHETIC_REPAIR_COOLDOWN_SEC = 300