version: '3.8'

# ======== health check, rollback =========

x-healthcheck-common: &healthcheck-common
  test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/readyz').read()"]
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 10s

x-deploy-common: &deploy-common
  replicas: 2
  update_config:
    parallelism: 1
    delay: 10s
    order: start-first
    failure_action: rollback
  restart_policy:
    condition: on-failure
    max_attempts: 3
  resources:
    limits:
      cpus: "1.00"
      memory: 512M
    reservations:
      cpus: "0.25"
      memory: 128M


services:
  control-api:
    image: harbor.lannister-dev.ru/vpn-service/control-api:${IMAGE_TAG:-latest}
    command:
      - uvicorn
      - app:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --proxy-headers
      - --forwarded-allow-ips=*
    deploy:
      <<: *deploy-common
      placement:
        constraints:
          - node.role == manager
      labels:
         # --------- Traefik ---------
        - "traefik.enable=true"
        - "traefik.http.routers.vpn-control-api.rule=Host(`api.lannister-dev.ru`) && PathPrefix(`/api`)"
        - "traefik.http.routers.vpn-control-api.entrypoints=websecure"
        - "traefik.http.routers.vpn-control-api.service=vpn-control-api"
        - "traefik.http.services.vpn-control-api.loadbalancer.server.port=8000"

        # -------- Prometheus --------
        - "prometheus-scrape=true"
        - "prometheus-app=control-api"
        - "prometheus-env=monitoring"
        - "prometheus-monitoring-port=8000"
        - "prometheus-monitoring-path=/api/monitoring"
        - "prometheus-scrape-profile=important"
    healthcheck: *healthcheck-common
    networks:
      - monitoring
      - traefik_swarm
    env_file:
      - .env

networks:
  monitoring:
    external: true
  traefik_swarm:
    external: true
