NOTIFICATIONS_MAX_AGE_S = 86400
NOTIFICATIONS_MAX_MSGS_PER_SUBJECT = 100_000
NOTIFICATIONS_DUPLICATE_WINDOW_S = 120

PROVIDER_FAILURE_WINDOW_S = 300
PROVIDER_FAILURE_THRESHOLD = 5
PROVIDER_FAILURE_ALERT_COOLDOWN_S = 1800
