"""added auth_token_hash to VpnNode

Revision ID: 25ac717c7aff
Revises: 5200c7c3113b
Create Date: 2026-01-23 18:20:35.911507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ac717c7aff'
down_revision: Union[str, None] = '5200c7c3113b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_node', sa.Column('auth_token_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_vpn_node_auth_token_hash'), 'vpn_node', ['auth_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_node_auth_token_hash'), table_name='vpn_node')
    op.drop_column('vpn_node', 'auth_token_hash')
    # ### end Alembic commands ###
