"""removed bad columns from VpnNode

Revision ID: 5200c7c3113b
Revises: e5cc808c599d
Create Date: 2026-01-22 22:35:49.988040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5200c7c3113b'
down_revision: Union[str, None] = 'e5cc808c599d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_assignment', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('vpn_key', sa.Column('xray_user_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('vpn_key_client_id_key'), 'vpn_key', type_='unique')
    op.create_unique_constraint(None, 'vpn_key', ['xray_user_id'])
    op.drop_column('vpn_key', 'client_id')
    op.drop_column('vpn_node', 'last_seen_at')
    op.drop_column('vpn_node', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_node', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('vpn_node', sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('vpn_key', sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vpn_key', type_='unique')
    op.create_unique_constraint(op.f('vpn_key_client_id_key'), 'vpn_key', ['client_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vpn_key', 'xray_user_id')
    op.drop_column('key_assignment', 'status')
    # ### end Alembic commands ###
