"""Add op_version/attempts/next_retry_at + indexes + server_default is_revoked

Revision ID: a97a3ab27149
Revises: bd4f6c1722e8
Create Date: 2026-01-25 15:06:33.915748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97a3ab27149'
down_revision: Union[str, None] = 'bd4f6c1722e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_assignment', sa.Column('op_version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('key_assignment', sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('key_assignment', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.create_index('ix_key_assignment_key_id', 'key_assignment', ['key_id'], unique=False)
    op.create_index('ix_key_assignment_next_retry_at', 'key_assignment', ['next_retry_at'], unique=False)
    op.create_index('ix_key_assignment_node_id', 'key_assignment', ['node_id'], unique=False)
    op.create_index('ix_key_assignment_status', 'key_assignment', ['status'], unique=False)
    op.create_index('ix_vpn_key_is_revoked', 'vpn_key', ['is_revoked'], unique=False)
    op.create_index('ix_vpn_key_user_id', 'vpn_key', ['user_id'], unique=False)
    op.create_index('ix_vpn_key_valid_until', 'vpn_key', ['valid_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vpn_key_valid_until', table_name='vpn_key')
    op.drop_index('ix_vpn_key_user_id', table_name='vpn_key')
    op.drop_index('ix_vpn_key_is_revoked', table_name='vpn_key')
    op.drop_index('ix_key_assignment_status', table_name='key_assignment')
    op.drop_index('ix_key_assignment_node_id', table_name='key_assignment')
    op.drop_index('ix_key_assignment_next_retry_at', table_name='key_assignment')
    op.drop_index('ix_key_assignment_key_id', table_name='key_assignment')
    op.drop_column('key_assignment', 'next_retry_at')
    op.drop_column('key_assignment', 'attempts')
    op.drop_column('key_assignment', 'op_version')
    # ### end Alembic commands ###
