"""added column details to NodeAgentState

Revision ID: b0da13659d3e
Revises: e18226a826df
Create Date: 2026-02-01 21:57:11.154400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0da13659d3e'
down_revision: Union[str, None] = 'e18226a826df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_agent_state', sa.Column('details', sa.JSON(), nullable=False))
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.create_index('ix_subscription_token_hash', 'subscription', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_token_hash', table_name='subscription')
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=True)
    op.drop_column('node_agent_state', 'details')
    # ### end Alembic commands ###
