"""add Subscription

Revision ID: b533ed7802f1
Revises: df809f8768b8
Create Date: 2026-01-28 21:54:17.564673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b533ed7802f1'
down_revision: Union[str, None] = 'df809f8768b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_token_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('profile_key', sa.String(length=64), nullable=True),
    sa.Column('preferred_region', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prev_token_hash')
    )
    op.create_index(op.f('ix_subscription_client_id'), 'subscription', ['client_id'], unique=False)
    op.create_index('ix_subscription_prev_token_hash', 'subscription', ['prev_token_hash'], unique=False)
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=True)
    op.create_index('ix_subscription_user_id', 'subscription', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_user_id', table_name='subscription')
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.drop_index('ix_subscription_prev_token_hash', table_name='subscription')
    op.drop_index(op.f('ix_subscription_client_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
