"""changed xray_user_id to client_id

Revision ID: bd4f6c1722e8
Revises: 25ac717c7aff
Create Date: 2026-01-24 14:44:47.591881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4f6c1722e8'
down_revision: Union[str, None] = '25ac717c7aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_key', sa.Column('client_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('vpn_key_xray_user_id_key'), 'vpn_key', type_='unique')
    op.create_unique_constraint(None, 'vpn_key', ['client_id'])
    op.drop_column('vpn_key', 'xray_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_key', sa.Column('xray_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vpn_key', type_='unique')
    op.create_unique_constraint(op.f('vpn_key_xray_user_id_key'), 'vpn_key', ['xray_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vpn_key', 'client_id')
    # ### end Alembic commands ###
