"""added is_enabled, is_draining, capacity columns

Revision ID: d03d1b2456b9
Revises: dbba43456b24
Create Date: 2026-02-10 20:45:55.455505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03d1b2456b9'
down_revision: Union[str, None] = 'dbba43456b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=True)
    op.add_column('vpn_node', sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('vpn_node', sa.Column('is_draining', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('vpn_node', sa.Column('capacity', sa.Integer(), server_default=sa.text('100'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_node', 'capacity')
    op.drop_column('vpn_node', 'is_draining')
    op.drop_column('vpn_node', 'is_enabled')
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=False)
    # ### end Alembic commands ###
