"""add ProfileArtifact table

Revision ID: df809f8768b8
Revises: a97a3ab27149
Create Date: 2026-01-25 22:07:00.028157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df809f8768b8'
down_revision: Union[str, None] = 'a97a3ab27149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_artifacts',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('artifact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_artifacts')
    # ### end Alembic commands ###
