"""added column last_ssen_at and agent_version in NodeAgentState

Revision ID: e18226a826df
Revises: 6ee8bf4531c5
Create Date: 2026-02-01 21:40:24.161122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18226a826df'
down_revision: Union[str, None] = '6ee8bf4531c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_agent_state', sa.Column('agent_version', sa.String(length=32), nullable=False))
    op.add_column('node_agent_state', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_token_hash'), table_name='subscription')
    op.create_index(op.f('ix_subscription_token_hash'), 'subscription', ['token_hash'], unique=False)
    op.drop_column('node_agent_state', 'last_seen_at')
    op.drop_column('node_agent_state', 'agent_version')
    # ### end Alembic commands ###
