SUPPORT_INBOUND_SUBJECT = "support.message.in"
SUPPORT_OUTBOUND_SUBJECT = "support.message.out"
SUPPORT_SENT_SUBJECT = "support.message.sent"
SUPPORT_TICKET_EVENT_SUBJECT = "support.ticket.event"

REOPEN_WINDOW_MIN = 60

SUBJECT_PREVIEW_LEN = 80

MAX_BROADCAST_DISPATCH_ATTEMPTS = 5
BROADCAST_RETRY_BACKOFF_SEC = 120
BROADCAST_SENDING_STALE_SEC = 300
