SUPPORT_INBOUND_SUBJECT = "support.message.in"
SUPPORT_OUTBOUND_SUBJECT = "support.message.out"
SUPPORT_TICKET_EVENT_SUBJECT = "support.ticket.event"

REOPEN_WINDOW_MIN = 60

SUBJECT_PREVIEW_LEN = 80
