name: Deploy Control API

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: tests
    runs-on: [ self-hosted, prod ]
    environment:
      name: production
    env:
      IMAGE_NAME: control-api
    steps:
      - uses: actions/checkout@v4
      - name: Prepare runtime
        uses: ./.github/workflows/runtime
        with:
          vault_scope: prod
          vault_addr: ${{ vars.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
          env_file: .env.prod
      - name: Set image tag
        run: |
          set -Eeuo pipefail
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
      - name: Build image
        run: |
          set -Eeuo pipefail
          docker build \
            -t "${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}" \
            -t "${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:prod" \
            .
      - name: Push image
        run: |
          set -Eeuo pipefail
          docker push "${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:prod"
      - name: Deploy Swarm
        run: |
          set -Eeuo pipefail
          docker stack deploy --with-registry-auth --prune -c docker-compose.yml control-api
      - name: Cleanup temporary env
        if: always()
        run: rm -f .env.prod
