name: Deploy Control API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      IMAGE_NAME: control-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Write .env (production)
        run: |
          echo "${{ secrets.CONTROL_API_ENV_PROD }}" > .env
      - name: Login to Harbor
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          echo "$HARBOR_PASSWORD" | docker login \
            ${{ secrets.HARBOR_URL }} \
            -u "$HARBOR_USERNAME" \
            --password-stdin
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:${IMAGE_TAG} \
            -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:prod \
            .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:prod
      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MANAGER_HOST }}
          username: root
          key: ${{ secrets.MANAGER_SSH }}
          envs: IMAGE_TAG
          script: |
            set -e
            cd /opt/control-api
            echo "${{ secrets.CONTROL_API_ENV_PROD }}" > .env

            docker stack deploy \
              --with-registry-auth \
              --prune \
              -c docker-compose.yml \
              control-api
